backend:
    name: git-gateway
    branch: master

media_folder: "src/static/images/uploads"
public_folder: "/images/uploads"

collections:
    - label: "Pages"
      name: "pages"
      editor:
        preview: false
      files:
        - label: "Master"
          name: "master"
          file: "src/content/master.md"
          fields:
            - { label: "Title", name: "title", widget: "string" }
            - { label: "Footer", name: "footer", widget: "markdown" }
        - label: "Home Page"
          name: "home"
          file: "src/content/_index.md"
          fields:
            - { label: "Title", name: "title", widget: "string" }
            - { label: "Image", name: "image", widget: "image" }